commonLabels:
  environment: "dev"
  managed-by: "harness-appset"
  demo-mode: "true"
image:
  registry: "docker.io"
  tag: "1.25.3-debian-11-r0"
  repository: "bitnami/nginx"
replicaCount: 2
service:
  type: "ClusterIP"
  ports:
    http: 80
html:
  enabled: true
  content: "<html>\n  <body>\n    <h1>Harness + OCI Demo</h1>\n    <p>This was deployed\
    \ using an OCI Helm Chart and Git-based values!</p>\n  </body>\n</html>\n"
